// <auto-generated />
using LaboratoryServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaboratoryServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201207235202_InitialMigraton")]
    partial class InitialMigraton
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LaboratoryServer.Model.Result", b =>
                {
                    b.Property<int>("IdResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Asp")
                        .HasColumnType("float");

                    b.Property<string>("DateOfPerform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<double>("Pc")
                        .HasColumnType("float");

                    b.Property<double>("Rbc")
                        .HasColumnType("float");

                    b.Property<string>("Technician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Wbc")
                        .HasColumnType("float");

                    b.HasKey("IdResult");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            IdResult = 1,
                            Asp = 99.0,
                            DateOfPerform = "12/12/12",
                            IdPatient = 1,
                            Pc = 345.0,
                            Rbc = 99.0,
                            Technician = "dr Mirosław Mirosławski",
                            Wbc = 12.0
                        },
                        new
                        {
                            IdResult = 2,
                            Asp = 1.0,
                            DateOfPerform = "11/11/11",
                            IdPatient = 2,
                            Pc = 123.0,
                            Rbc = 99.0,
                            Technician = "dr AAAAAA AAAAAA",
                            Wbc = 122.0
                        },
                        new
                        {
                            IdResult = 3,
                            Asp = 22222.0,
                            DateOfPerform = "12/01/09",
                            IdPatient = 3,
                            Pc = 6544.0,
                            Rbc = 99.0,
                            Technician = "dr Placeholder",
                            Wbc = 132.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
