// <auto-generated />
using LaboratoryServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaboratoryServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210108223001_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LaboratoryServer.Model.Result", b =>
                {
                    b.Property<int>("IdResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Blasts")
                        .HasColumnType("float");

                    b.Property<string>("DateOfPerform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HCT")
                        .HasColumnType("float");

                    b.Property<double>("HGB")
                        .HasColumnType("float");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<double>("Platelets")
                        .HasColumnType("float");

                    b.Property<double>("RBC")
                        .HasColumnType("float");

                    b.Property<double>("Segs")
                        .HasColumnType("float");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WBC")
                        .HasColumnType("float");

                    b.HasKey("IdResult");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            IdResult = 1,
                            Blasts = 99.0,
                            DateOfPerform = "01/04/12",
                            HCT = 35.0,
                            HGB = 4.4000000000000004,
                            IdPatient = 1,
                            Platelets = 1.3,
                            RBC = 3.3999999999999999,
                            Segs = 55.0,
                            Technician = "dr Paweł Jakubowski",
                            WBC = 1.3999999999999999
                        },
                        new
                        {
                            IdResult = 2,
                            Blasts = 19.0,
                            DateOfPerform = "09/11/2019",
                            HCT = 33.0,
                            HGB = 7.4000000000000004,
                            IdPatient = 1,
                            Platelets = 2.2999999999999998,
                            RBC = 2.3999999999999999,
                            Segs = 75.0,
                            Technician = "de Przemysław Czerwiński",
                            WBC = 1.3
                        },
                        new
                        {
                            IdResult = 3,
                            Blasts = 77.0,
                            DateOfPerform = "12/12/12",
                            HCT = 45.0,
                            HGB = 8.4000000000000004,
                            IdPatient = 1,
                            Platelets = 2.3999999999999999,
                            RBC = 4.4000000000000004,
                            Segs = 57.0,
                            Technician = "dr Kamil Kołecki",
                            WBC = 1.7
                        },
                        new
                        {
                            IdResult = 4,
                            Blasts = 89.0,
                            DateOfPerform = "12/05/12",
                            HCT = 45.0,
                            HGB = 4.4000000000000004,
                            IdPatient = 1,
                            Platelets = 4.2999999999999998,
                            RBC = 4.4000000000000004,
                            Segs = 54.0,
                            Technician = "dr Łukasz Szymczak",
                            WBC = 2.3999999999999999
                        },
                        new
                        {
                            IdResult = 5,
                            Blasts = 99.0,
                            DateOfPerform = "01/01/12",
                            HCT = 35.0,
                            HGB = 4.4000000000000004,
                            IdPatient = 2,
                            Platelets = 1.3,
                            RBC = 3.3999999999999999,
                            Segs = 55.0,
                            Technician = "dr Radosław Mirosław",
                            WBC = 1.3999999999999999
                        });
                });

            modelBuilder.Entity("LaboratoryServer.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pierwszy@email.com",
                            Name = "Pierwszy",
                            Password = "pierwszy",
                            Surname = "Użytkownik"
                        },
                        new
                        {
                            Id = 2,
                            Email = "drugi@email.com",
                            Name = "Drugi",
                            Password = "drugi",
                            Surname = "Użytkownik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
